### ISSUE TITLE
Update README.md - easier installation

### ISSUE THREAD

**Issue by TomFreudenberg** [team-flit/raspi-light-react-meteor#1]
Hi, I updated the guide for installation

See the new one at:

http://meteor-universal.tumblr.com/post/132266856859/1st-time-installation-meteor-12x-universal-raspbian

You may change your README infos just to. Node is already include now in the dev_bundles:

---
# How to install
### Setup Raspberry pi and install Meteor

http://meteor-universal.tumblr.com/post/132266856859/1st-time-installation-meteor-12x-universal-raspbian

**Comment by TomFreudenberg** [comment]
Also the `Known issues` are documented or not existing anymore :-)

**Comment by colus001** [comment]
@TomFreudenberg Thanks. :D Updated :+1:

**Comment by TomFreudenberg** [comment]
Hi, you do also don't need that info block anymore:

In the new meteor-universal, node 0.10.40 is already included

---

Install Meteor on Raspberry Pi

It seems like node 0.10.38 version is not working for meteor 1.2. Before run $ meteor --version don't forget to install v0.10.40 of node.js.

```
Download 0.10.40 and follow instruction
```

---
